FROM ubuntu:latest

RUN apt-get -q update && apt-get upgrade -y && \
    apt-get install -y -qq curl bash ca-certificates

COPY . /app
WORKDIR /app

RUN chmod +x src/install_rust.sh src/uninstall_rust.sh script.sh

# The bashrc autogenerated file contains the following 2 lines:
#     # If not running interactively, don't do anything
#     [ -z "$PS1" ] && return
# This means that if the shell is not interactive, it will not run the script. This breaks the source ~/.bashrc command.
# We can use the -i (interactive) option to force the shell to be interactive (this is not -it (interactive docker session) as it is not a TTY).
#     The -i option will force the shell to source the .bashrc file and it sets the PS1 variable.
#     However, this will produce a warning messages:
#         bash: cannot set terminal process group (-1): Inappropriate ioctl for device
#         bash: no job control in this shell
#     This is not a problem, as we are not using job control in this script. Just deal with it.
# To simulate the real user environment, we will use the -l (login) option to force the shell to be a login shell.
#     This will source the profiile file
CMD ["bash", "-l", "-i", "./script.sh"]

