site_name: Linux Rootless DevKit
nav:
  - Overview:
    - index.md
  - User:
    - Modules:
        - Rust:
            user/modules/rust.md
        - Go:
            user/modules/go.md
        - OhMyBash:
            user/modules/ohmybash.md
        - OhMyZsh:
            user/modules/ohmyzsh.md
        - MkDocs:
            user/modules/mkdocs.md
  - Developer:
    - Help:
        - MkDocs:
            developer/help/mkdocs.md
        - Markdown:
            developer/help/markdown.md
theme:
  name: material
  favicon: images/RootlessDevkit_logo.png
  features:
    - content.tooltips
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      toc_depth: 2
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-authors:
      show_contribution: true
      authorship_threshold_percent: 20
      fallback_to_empty: true
      enabled_on_serve: true
  - search:
      lang: en
  - literate-nav:
      implicit_index: true
  - d2:
      scale: 0.8
      pad: 10
      theme: 0
      layout: elk


validation:
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn