FROM ubuntu:latest

RUN apt-get -q update && apt-get upgrade -y && \
    apt-get install -y -qq\
			bash\
			gcc g++\
			clang\
			curl\
			ca-certificates\
			xz-utils\
			git\
			make\
			gcc\
			fontconfig\
			libncurses-dev\
			tree\
			nano &&\
			echo "set linenumbers" >> /etc/nanorc


# --- Install make 4.4.1 ---
RUN curl -LO https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz && \
    tar -xzf make-4.4.1.tar.gz && \
    cd make-4.4.1 && \
    ./configure --prefix=/usr/local && \
    make -j$(nproc) && \
    make install && \
    cd .. && rm -rf make-4.4.1 make-4.4.1.tar.gz && \
    make --version

# --- Install Go 1.24.1 ---
ENV GO_VERSION=1.24.1
RUN curl -sSL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz -o go.tar.gz && \
    tar -C /usr/local -xzf go.tar.gz && \
    rm go.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/local/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt && \
    go version

# --- Install golangci_lint 1.64.5 ---
ENV GOLANGCI_LINT_VERSION=v1.64.5
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
    sh -s -- -b /usr/local/bin ${GOLANGCI_LINT_VERSION} && \
    ls -lh /usr/local/bin/golangci-lint && \
    golangci-lint --version

# --- Install Docker CLI 27.2.1 ---
ENV DOCKER_VERSION=27.2.1
RUN curl -LO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz && \
    tar -xzf docker-${DOCKER_VERSION}.tgz && \
    cp docker/docker /usr/local/bin/ && \
    rm -rf docker docker-${DOCKER_VERSION}.tgz && \
    docker --version

# --- Install Docker Compose v2.32.1 ---
ENV DOCKER_COMPOSE_VERSION=2.32.1

RUN curl -SL https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64 \
    -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    ln -s /usr/local/bin/docker-compose /usr/local/bin/docker-compose-v2 && \
    docker-compose version

COPY . /app
WORKDIR /app

RUN chmod +x src/install_rust.sh src/uninstall_rust.sh script.sh
RUN chmod +x src/zsh/zshUninstall.sh src/zsh/zshInstall.sh

CMD ["bash", "-l", "-i", "./script.sh"]
