# DOCKER_BUILDKIT=1 docker build --no-cache --file test/docker/Dockerfile_ubuntu_latest --tag test-ubuntu:latest .
# docker run --rm -i -t test-ubuntu:latest

FROM ubuntu:latest AS tester

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        bash \
        gcc \
        g++ \
        curl \
        ca-certificates \
        xz-utils \
        git \
        make \
        cmake \
        fontconfig \
        libncurses-dev \
        shellcheck \
        locales && \
        apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

COPY . /app
WORKDIR /app

# =============== Simulate user without root privileges (no sudo) ===============

RUN groupadd -f -g 1111 tester-wo-root && \
    useradd -m -u 1111 -g tester-wo-root tester-wo-root

RUN chgrp -R tester-wo-root /app /tmp && \
    chmod -R g+rwx /app /tmp

USER tester-wo-root

# ===============================================================================

ENTRYPOINT ["bash", "--login", "-i", "./script.sh"]
