# DOCKER_BUILDKIT=1 docker build --no-cache --file  ./test/apps_isolated/docker/Dockerfile_isolated_test_redhat --tag tests-redhat:apps-isolated .
# docker run --rm -t -v /etc/group:/etc/group:ro -v /var/run/docker.sock:/var/run/docker.sock --group-add $(stat -c '%g' /var/run/docker.sock) tests-redhat:apps-isolated

FROM registry.access.redhat.com/ubi8/ubi:8.6 AS tester

LABEL maintainer="Michal Kukowski - KukosSW"

USER root

ENV GOBIN=/usr/lib/docker/cli-plugins

RUN dnf -y module enable container-tools && \
    dnf -y install \
        glibc-langpack-en \
        ca-certificates \
        sudo \
        git \
        curl \
        gawk \
        glibc-langpack-en

ENV container=docker
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN DOCKER_VERSION=$(curl -fsSL https://download.docker.com/linux/static/stable/x86_64/ | \
                     grep -oE 'docker-[0-9]+\.[0-9]+\.[0-9]+\.tgz' | \
                     sed -E 's/docker-([0-9]+\.[0-9]+\.[0-9]+)\.tgz/\1/' | \
                     sort -Vr | \
                     head -n1) && \
    curl -fsSL "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" -o /tmp/docker.tgz && \
    tar -C /usr/local/bin --strip-components=1 -xzf /tmp/docker.tgz docker/docker && \
    chmod +x /usr/local/bin/docker && \
    rm /tmp/docker.tgz

RUN mkdir -p ${GOBIN}

RUN LATEST_GO_TAG=$(curl -fsSL https://go.dev/VERSION?m=text | head -n 1) && \
    curl -fsSL "https://dl.google.com/go/${LATEST_GO_TAG}.linux-amd64.tar.gz" -o /tmp/go.tar.gz && \
    tar -C /usr/local -xzf /tmp/go.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/bin/gofmt && \
    rm /tmp/go.tar.gz

WORKDIR /tmp
RUN LATEST_DOCKER_BUILDX_TAG=$(git ls-remote --tags --refs  https://github.com/docker/buildx.git | \
                               awk '{print $2}' | \
                               awk -F '/' '{print $3}' | \
                               grep "^v" | \
                               grep -v "rc" | \
                               sort -Vr | \
                               head -n 1) && \
    git clone --depth 1 --branch "${LATEST_DOCKER_BUILDX_TAG}" https://github.com/docker/buildx.git

WORKDIR /tmp/buildx
RUN go mod download && \
    go build -o docker-buildx ./cmd/buildx && \
    mv docker-buildx ${GOBIN}/docker-buildx && \
    chmod +x ${GOBIN}/docker-buildx

RUN groupadd -f -g 999 docker && \
    useradd -m -u 1111 -g docker tester-wo-root && \
    echo "tester-wo-root ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/tester-wo-root && \
    chmod 0440 /etc/sudoers.d/tester-wo-root

USER tester-wo-root

COPY . /src
WORKDIR /src

ENTRYPOINT ["/src/test/apps_isolated/test_main.sh"]